### PR TITLE
new chargestate 'notReadyForCharging'

### PR DESCRIPTION
**Pull request by thiasB**
from ID Software 3.0 on chargestate switches from `readyForCharging` to newly introduced status `notReadyForCharging` when unplugging the car.

### CODE REVIEW

**Comment by robske110** [comment]
I made some whitespace and commit message changes to your commit.
I also added the new states to the iOS widget, to the chargingSession logic (and chargeStart detection), and added a fallback to the old value (we still need to support pre 3.0 cars & for chargingSessions the old db values need to be able to still be processed.
TODO: CarStatusFetcher should possibly always use the increased-updaterate if plugged in, not just while charging.

**Comment by robske110** [comment]
It would be nice if we could get some testing done on these changes.
Please also run
```sudo su postgres -c "psql -d vwid -c \"DELETE FROM chargingSessions;\""
sudo systemctl restart iddatalogger.service```
to reset the charging sessions, because since 3.0 they will have been generated incorrectly.

**Comment by thiasB** [comment]
Seems to work. The only warnings I get are about three status flagss in carStatus data:
```
[NOTICE] Could not find expected key 'hvacWithoutExternalPower' in carStatusData. Unexpected changes in older or newer car software can cause this!
[NOTICE] Could not find expected key 'zoneRearLeftEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
[NOTICE] Could not find expected key 'zoneRearRightEnabled' in carStatusData. Unexpected changes in older or newer car softwar.e can cause this!
```

Let me know what input you are looking for to get this solved before merging

**Comment by robske110** [comment]
Well these three warnings are unrelated to this. The first key is gone for good probably, the last two are only present on ID.4 (4-zone climate control vehicles)

**Pull request merged**
