### PR TITLE
Charge sessions

### PR DESCRIPTION
**Pull request by robske110**
Screenshot of the new charge Session feature:
image
Feel free to test this if you want to help me out! Any feedback on anything (including the design is very appreciated)
Commands for updating standard installations:
```
cd ~/IDDataLogger
git fetch
git checkout charge-sessions
sudo rm -r /var/www/html/vwid/
sudo cp -r ./public/. /var/www/html/vwid
```
Followed by a system restart (or just the service).
Then go to https://host:port/vwid/idView/chargingOverview.html (or just the Charging Sessions tab in the IDView you already know)

TODO:
- [x] Navigation in IDView
- [x] implement proper refresh
- [x] Fix scrolling bugs
- [ ] Fix updates when not on screen breaking Chart.js

There is still a lot of "wanted functionality" that has not been implemented yet:
- [ ] Graph of "only" the charging session (-> detail page maybe)
- [ ] CSV download
- [ ] date range selectable (and maybe pagination)

This PR will be merged soon anyway to prevent further diverging of the branches, which significantly slowed down development and increased complexity.

### CODE REVIEW

**Comment by korhojoa** [comment]
Hi, tried your charge-sessions branch, and it did this:

`:~/IDDataLogger$ ./start.sh
Loading Logger...
08:46:07.244757 [INFO] Starting ID DataLogger Version v0.0.5-InDev (51b8c14790f94bb4436c7a8aa6f5df0d2955820e)...
Loading Main...
08:46:07.890871 [INFO] Reading config...
08:46:07.891156 [INFO] Connecting to db...
Loading DatabaseConnection...
Loading QueryCreationHelper...
Loading DBmigrator...
08:46:08.476078 [NOTICE] Could not find settings table, upgrading schema to V1
08:46:08.476148 [INFO] Initializing db tables...
Loading CurlWrapper...
Loading API...
Loading CarPictureHandler...
Loading CarStatusWrittenUpdateReceiver...
Loading ChargeSessionHandler...
08:46:09.281644 [INFO] Building past charge sessions from beginning of data logging...
08:46:09.456429 [INFO] Plugged car in at 2021-04-20 09:41:36
Loading ChargeSession...
08:46:09.457396 [INFO] Started charging at 2021-04-20 09:46:34
08:46:09.457865 [INFO] Ended charging at 2021-04-20 10:46:15
08:46:09.457931 [INFO] Unplugged car at 2021-04-20 10:56:56
Loading ErrorUtils...
08:46:09.462664 [CRITICAL] TypeError: "round(): Argument #1 ($num) must be of type int|float, null given" (EXCEPTION) in "/home/joakim/IDDataLogger/src/vwid/chargesession/ChargeSession.php" at line 117
08:46:09.462774 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
08:46:09.462800 [INFO] Shutting down...
08:46:09.462821 [CRITICAL] Forcibly shutting down while starting!`

**Comment by robske110** [comment]
I mitigated the crash, can you please try again?
The crash happened because in that charging Session apparently there was never any charge Power reported.
Could you share your debug output of the first start after updating and check how the charge Session for the 20.04.2021 in the morning looks?

**Comment by korhojoa** [comment]
Now this: 
```
13:52:49.217861 [INFO] Building past charge sessions from beginning of data logging...
13:52:49.401576 [INFO] Plugged car in at 2021-04-20 09:41:36
Loading ChargeSession...
13:52:49.402331 [INFO] Started charging at 2021-04-20 09:46:34
13:52:49.402753 [INFO] Ended charging at 2021-04-20 10:46:15
13:52:49.402815 [INFO] Unplugged car at 2021-04-20 10:56:56
13:52:49.402889 [INFO] Charge session:
range: start: 13km end: 119km
duration: 1h
SOC: start: 18% end: 100% target: 0%
chargeEnergy:0kWh cE_soc_calc47.56kWh
NO chargePower
Loading ErrorUtils...
13:52:49.405040 [CRITICAL] Error: "Typed property robske_110\vwid\chargesession\ChargeSession::$avgChargeKMR must not be accessed before initialization" (EXCEPTION) in "/home/joakim/IDDataLogger/src/vwid/chargesession/ChargeSession.php" at line 124
13:52:49.405185 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
13:52:49.405227 [INFO] Shutting down...
13:52:49.405269 [CRITICAL] Forcibly shutting down while starting!
```

**Comment by robske110** [comment]
The displayed data looks very weird. A range of 119km at 100%? The charge target of 0%?
What car do you have? Missing targetSOC and chargePower are something that points to the vehicle not being an ID. family vehicle.
I attempted to fix the crash causing that issue. Please keep in mind that if you're using this project with a non-ID. car, I can only fix issues reported to me as I do not own such cars myself. I do appreciate the reports though!

**Comment by korhojoa** [comment]
Yes, it's not a ID car, it is a e-Golf. Now, however, it starts and seems to work.
image
```
 1 file changed, 3 insertions(+)
$ ./start.sh
Loading Logger...
09:01:04.282333 [INFO] Starting ID DataLogger Version v0.0.5-InDev (ae18b28e71dff6d252dbb48fd4ea62372db5bfbb)...
Loading Main...
09:01:04.966635 [INFO] Reading config...
09:01:04.967009 [INFO] Connecting to db...

Loading DatabaseConnection...
Loading QueryCreationHelper...
Loading DBmigrator...
Loading CurlWrapper...
Loading API...
Loading CarPictureHandler...
Loading CarStatusWrittenUpdateReceiver...
Loading ChargeSessionHandler...
09:01:06.120028 [INFO] Building past charge sessions from beginning of data logging...
09:01:06.280230 [INFO] Plugged car in at 2021-04-20 09:41:36
Loading ChargeSession...
09:01:06.280884 [INFO] Started charging at 2021-04-20 09:46:34
09:01:06.281545 [INFO] Ended charging at 2021-04-20 10:46:15
09:01:06.281603 [INFO] Unplugged car at 2021-04-20 10:56:56
09:01:06.281713 [INFO] Charge session:
range: start: 13km end: 119km
duration: 1h
SOC: start: 18% end: 100% target: 0%
chargeEnergy:0kWh cE_soc_calc47.56kWh
NO chargePower
Loading CarStatusFetcher...
09:01:06.404790 [INFO] Logging in...
Loading LoginInformation...
Loading MobileAppAPI...
Loading HTTPUtils...
Loading Form...
Loading CarStatusUpdateReceiver...
Loading CarStatusWriter...
09:01:11.396925 [INFO] Done. Startup took 7.2663841247559s
09:01:11.396973 [INFO] Ready!
09:01:11.396996 [INFO] Fetching car status...
09:01:13.391370 [NOTICE] Could not find expected key 'chargePower' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391433 [NOTICE] Could not find expected key 'chargeRateKMPH' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391455 [NOTICE] Could not find expected key 'autoUnlockPlugWhenCharged' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391479 [NOTICE] Could not find expected key 'targetSOC' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391499 [NOTICE] Could not find expected key 'hvacAtUnlock' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391528 [NOTICE] Could not find expected key 'windowHeatingEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391557 [NOTICE] Could not find expected key 'zoneFrontLeftEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391586 [NOTICE] Could not find expected key 'zoneFrontRightEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391614 [NOTICE] Could not find expected key 'zoneRearLeftEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391642 [NOTICE] Could not find expected key 'zoneRearRightEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:01:13.391672 [INFO] Writing new data for timestamp 2021-04-22T05:37:07
```

Excellent!

**Comment by robske110** [comment]
Nice. But since your car sends no chargePower the power and chargeKWh columns will unfortunately always show 0.
Apart from that, what do you think about the interface? (What could be improved, suggestions etc.)

**Comment by korhojoa** [comment]
Heh, me too!
The interface is fine, I haven't used it much yet due to the current circumstance, I mostly set this up so I would have at least some data logging from my car.
It seems that the car-net and we connect have different data available.
It doesn't report what the charging power is, but it does report how long the charge is expected to take and what current it is charging at. 
It would be interesting to have door, window, trunk and bonnet status too. (Not sure if ID.'s provide this) From debug:
```
array(11) {
  ["accessStatus"]=>
  array(4) {
    ["overallStatus"]=>
    string(6) "unsafe"
    ["carCapturedTimestamp"]=>
    string(20) "2021-04-22T06:14:43Z"
    ["doors"]=>
    array(6) {
      [0]=>
      array(2) {
        ["name"]=>
        string(6) "bonnet"
        ["status"]=>
        array(1) {
          [0]=>
          string(4) "open"
        }
      }
      [1]=>
      array(2) {
        ["name"]=>
        string(9) "frontLeft"
        ["status"]=>
        array(2) {
          [0]=>
          string(8) "unlocked"
          [1]=>
          string(6) "closed"
        }
      }
      [2]=>
      array(2) {
        ["name"]=>
        string(10) "frontRight"
        ["status"]=>
        array(2) {
          [0]=>
          string(8) "unlocked"
          [1]=>
          string(6) "closed"
        }
      }
      [3]=>
      array(2) {
        ["name"]=>
        string(8) "rearLeft"
        ["status"]=>
        array(2) {
          [0]=>
          string(8) "unlocked"
          [1]=>
          string(6) "closed"
        }
      }
      [4]=>
      array(2) {
        ["name"]=>
        string(9) "rearRight"
        ["status"]=>
        array(2) {
          [0]=>
          string(8) "unlocked"
          [1]=>
          string(6) "closed"
        }
      }
      [5]=>
      array(2) {
        ["name"]=>
        string(5) "trunk"
        ["status"]=>
        array(2) {
          [0]=>
          string(8) "unlocked"
          [1]=>
          string(6) "closed"
        }
      }
    }
    ["windows"]=>
    array(6) {
      [0]=>
      array(2) {
        ["name"]=>
        string(9) "frontLeft"
        ["status"]=>
        array(1) {
          [0]=>
          string(4) "open"
        }
      }
      [1]=>
      array(2) {
        ["name"]=>
        string(10) "frontRight"
        ["status"]=>
        array(1) {
          [0]=>
          string(6) "closed"
        }
      }
      [2]=>
      array(2) {
        ["name"]=>
        string(8) "rearLeft"
        ["status"]=>
        array(1) {
          [0]=>
          string(6) "closed"
        }
      }
      [3]=>
      array(2) {
        ["name"]=>
        string(9) "rearRight"
        ["status"]=>
        array(1) {
          [0]=>
          string(6) "closed"
        }
      }
      [4]=>
      array(2) {
        ["name"]=>
        string(9) "roofCover"
        ["status"]=>
        array(1) {
          [0]=>
          string(11) "unsupported"
        }
      }
      [5]=>
      array(2) {
        ["name"]=>
        string(7) "sunRoof"
        ["status"]=>
        array(1) {
          [0]=>
          string(11) "unsupported"
        }
      }
    }
  }
  ["batteryStatus"]=>
```

**Comment by robske110** [comment]
Great! Yea, unfortunately ID. vehicles do not provide door status. Implementing it will not be a priority for me at the moment.

**Comment by korhojoa** [comment]
Not sure if this was related, I can put this in a different issue if desired, but had another crash (before the timezone change)

```
}
09:37:10.749300 [DEBUG] Ignored content at lightsStatus
09:37:10.749398 [DEBUG] Ignored content at capabilityStatus
PHP Warning:  Undefined array key "chargeState" in /home/joakim/IDDataLogger/src/vwid/CarStatusFetcher.php on line 88
09:37:10.749524 [NOTICE] Could not find expected key 'batteryStatusTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.749620 [NOTICE] Could not find expected key 'chargingStatusTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.749714 [NOTICE] Could not find expected key 'chargingSettingsTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.749776 [NOTICE] Could not find expected key 'plugStatusTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.749853 [NOTICE] Could not find expected key 'climatisationStatusTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.749900 [NOTICE] Could not find expected key 'climatisationSettingsTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.749960 [NOTICE] Could not find expected key 'windowHeatingStatusTimestamp' in carStatusData. Unexpected changes in older or newer car software can cause this!
09:37:10.750054 [DEBUG] carStatusData:
array(0) {
}
09:37:10.750229 [CRITICAL] RuntimeException: "Data does not contain any timestamps, unable to write to db!" (EXCEPTION) in "/home/joakim/IDDataLogger/src/vwid/CarStatusWriter.php" at line 98
09:37:10.750298 [DEBUG] #0 /home/joakim/IDDataLogger/src/vwid/CarStatusWriter.php(74): robske_110\vwid\CarStatusWriter->writeCarStatus()
09:37:10.750339 [DEBUG] #1 /home/joakim/IDDataLogger/src/vwid/CarStatusFetcher.php(94): robske_110\vwid\CarStatusWriter->carStatusUpdate()
09:37:10.750380 [DEBUG] #2 /home/joakim/IDDataLogger/src/vwid/Main.php(90): robske_110\vwid\CarStatusFetcher->tick()
09:37:10.750441 [DEBUG] #3 /home/joakim/IDDataLogger/src/vwid/Server.php(114): robske_110\vwid\Main->tick()
09:37:10.750523 [INFO] Shutting down...
09:37:10.750607 [DEBUG] >Closing Logger...
```
carStatusData returned empty, and it didn't seem too happy about there being no time data there.

**Comment by robske110** [comment]
Was that just a one-time occurrence or did this happen multiple times?

**Comment by korhojoa** [comment]
Hi, one-time, so far, but it seems like the logger shouldn't quit/crash if there is a problem with the VW api. Here's a fuller snippet of that: 
```          bool(false)                                                                                                                                                                                                                                                                                                                                       │        }                                                                                                                                                                                                                                                                                                                                                   │        [40]=>                                                                                                                                                                                                                                                                                                                                              │        array(3) {                                                                                                                                                                                                                                                                                                                                          │          ["id"]=>                                                                                                                                                                                                                                                                                                                                          │          string(18) "weatherInformation"                                                                                                                                                                                                                                                                                                                   │          ["status"]=>                                                                                                                                                                                                                                                                                                                                      │          array(1) {                                                                                                                                                                                                                                                                                                                                        │            [0]=>                                                                                                                                                                                                                                                                                                                                           │            int(1008)                                                                                                                                                                                                                                                                                                                                       │          }                                                                                                                                                                                                                                                                                                                                                 │          ["userDisablingAllowed"]=>                                                                                                                                                                                                                                                                                                                        │          bool(false)                                                                                                                                                                                                                                                                                                                                       │        }                                                                                                                                                                                                                                                                                                                                                   │        [41]=>                                                                                                                                                                                                                                                                                                                                              │        array(3) {                                                                                                                                                                                                                                                                                                                                          │          ["id"]=>                                                                                                                                                                                                                                                                                                                                          │          string(8) "webRadio"                                                                                                                                                                                                                                                                                                                              │          ["status"]=>                                                                                                                                                                                                                                                                                                                                      │          array(1) {                                                                                                                                                                                                                                                                                                                                        ┤            [0]=>                                                                                                                                                                                                                                                                                                                                           │            int(1008)                                                                                                                                                                                                                                                                                                                                       │          }                                                                                                                                                                                                                                                                                                                                                 │          ["userDisablingAllowed"]=>                                                                                                                                                                                                                                                                                                                        │          bool(false)                                                                                                                                                                                                                                                                                                                                       │        }                                                                                                                                                                                                                                                                                                                                                   │      }                                                                                                                                                                                                                                                                                                                                                     │    }                                                                                                                                                                                                                                                                                                                                                       │  }                                                                                                                                                                                                                                                                                                                                                         │  ["error"]=>                                                                                                                                                                                                                                                                                                                                               │  array(6) {                                                                                                                                                                                                                                                                                                                                                │    ["accessStatus"]=>                                                                                                                                                                                                                                                                                                                                      │    array(5) {                                                                                                                                                                                                                                                                                                                                              │      ["code"]=>                                                                                                                                                                                                                                                                                                                                            │      int(4105)                                                                                                                                                                                                                                                                                                                                             │      ["message"]=>                                                                                                                                                                                                                                                                                                                                         │      string(48) "The underlying system is not responding properly"                                                                                                                                                                                                                                                                                         │      ["group"]=>                                                                                                                                                                                                                                                                                                                                           │      int(2)                                                                                                                                                                                                                                                                                                                                                │      ["info"]=>                                                                                                                                                                                                                                                                                                                                            │      string(92) "Internal error, please try again later. If the problem persists, please contact our support."                                                                                                                                                                                                                                             │      ["retry"]=>                                                                                                                                                                                                                                                                                                                                           │      bool(true)                                                                                                                                                                                                                                                                                                                                            │    }                                                                                                                                                                                                                                                                                                                                                       │    ["chargingSettings"]=>                                                                                                                                                                                                                                                                                                                                  │    array(5) {                                                                                                                                                                                                                                                                                                                                              │      ["code"]=>                                                                                                                                                                                                                                                                                                                                            │      int(4105)                                                                                                                                                                                                                                                                                                                                             │      ["message"]=>                                                                                                                                                                                                                                                                                                                                         │      string(48) "The underlying system is not responding properly"                                                                                                                                                                                                                                                                                         │      ["group"]=>                                                                                                                                                                                                                                                                                                                                           │      int(2)                                                                                                                                                                                                                                                                                                                                                │      ["info"]=>                                                                                                                                                                                                                                                                                                                                            │      string(92) "Internal error, please try again later. If the problem persists, please contact our support."                                                                                                                                                                                                                                             │      ["retry"]=>                                                                                                                                                                                                                                                                                                                                           │      bool(true)                                                                                                                                                                                                                                                                                                                                            │    }                                                                                                                                                                                                                                                                                                                                                       │    ["chargingStatus"]=>                                                                                                                                                                                                                                                                                                                                    │    array(5) {                                                                                                                                                                                                                                                                                                                                              │      ["code"]=>                                                                                                                                                                                                                                                                                                                                            │      int(4105)                                                                                                                                                                                                                                                                                                                                             │      ["message"]=>                                                                                                                                                                                                                                                                                                                                         │      string(48) "The underlying system is not responding properly"                                                                                                                                                                                                                                                                                         │      ["group"]=>                                                                                                                                                                                                                                                                                                                                           │      int(2)                                                                                                                                                                                                                                                                                                                                                │      ["info"]=>                                                                                                                                                                                                                                                                                                                                            │      string(92) "Internal error, please try again later. If the problem persists, please contact our support."                                                                                                                                                                                                                                             │      ["retry"]=>                                                                                                                                                                                                                                                                                                                                           │      bool(true)                                                                                                                                                                                                                                                                                                                                            │    }                                                                                                                                                                                                                                                                                                                                                       │    ["climatisationSettings"]=>                                                                                                                                                                                                                                                                                                                             │    array(5) {                                                                                                                                                                                                                                                                                                                                              │      ["code"]=>                                                                                                                                                                                                                                                                                                                                            │      int(4105)                                                                                                                                                                                                                                                                                                                                             │      ["message"]=>                                                                                                                                                                                                                                                                                                                                         │      string(48) "The underlying system is not responding properly"                                                                                                                                                                                                                                                                                         │      ["group"]=>                                                                                                                                                                                                                                                                                                                                           │      int(2)                                                                                                                                                                                                                                                                                                                                                │      ["info"]=>                                                                                                                                                                                                                                                                                                                                            │      string(92) "Internal error, please try again later. If the problem persists, please contact our support."                                                                                                                                                                                                                                             │      ["retry"]=>                                                                                                                                                                                                                                                                                                                                           │      bool(true)                                                                                                                                                                                                                                                                                                                                            │    }                                                                                                                                                                                                                                                                                                                                                       │    ["climatisationStatus"]=>                                                                                                                                                                                                                                                                                                                               │    array(5) {                                                                                                                                                                                                                                                                                                                                              │      ["code"]=>                                                                                                                                                                                                                                                                                                                                            │      int(4105)                                                                                                                                                                                                                                                                                                                                             │      ["message"]=>                                                                                                                                                                                                                                                                                                                                         │      string(48) "The underlying system is not responding properly"                                                                                                                                                                                                                                                                                         │      ["group"]=>                                                                                                                                                                                                                                                                                                                                           │      int(2)                                                                                                                                                                                                                                                                                                                                                │      ["info"]=>                                                                                                                                                                                                                                                                                                                                            │      string(92) "Internal error, please try again later. If the problem persists, please contact our support."                                                                                                                                                                                                                                             │      ["retry"]=>                                                                                                                                                                                                                                                                                                                                           │      bool(true)                                                                                                                                                                                                                                                                                                                                            │    }                                                                                                                                                                                                                                                                                                                                                       │    ["rangeStatus"]=>                                                                                                                                                                                                                                                                                                                                       │    array(5) {                                                                                                                                                                                                                                                                                                                                              │      ["code"]=>                                                                                                                                                                                                                                                                                                                                            │      int(4105)                                                                                                                                                                                                                                                                                                                                             │      ["message"]=>                                                                                                                                                                                                                                                                                                                                         │      string(48) "The underlying system is not responding properly"                                                                                                                                                                                                                                                                                         │      ["group"]=>                                                                                                                                                                                                                                                                                                                                           │      int(2)                                                                                                                                                                                                                                                                                                                                                │      ["info"]=>                                                                                                                                                                                                                                                                                                                                            │      string(92) "Internal error, please try again later. If the problem persists, please contact our support."                                                                                                                                                                                                                                             │      ["retry"]=>                                                                                                                                                                                                                                                                                                                                           │      bool(true)                                                                                                                                                                                                                                                                                                                                            │    }                                                                                                                                                                                                                                                                                                                                                       │  }                                                                                                                                                                                                                                                                                                                                                         │}                                                                                                                                                                                                                                                                                                                                                           │09:37:10.748491 [WARNING] VW API reported error while fetching car status: Array                                                                                                                                                                                                                                                                            │(                                                                                                                                                                                                                                                                                                                                                           │    [accessStatus] => Array                                                                                                                                                                                                                                                                                                                                 │        (                                                                                                                                                                                                                                                                                                                                                   │            [code] => 4105                                                                                                                                                                                                                                                                                                                                  │            [message] => The underlying system is not responding properly                                                                                                                                                                                                                                                                                   │            [group] => 2                                                                                                                                                                                                                                                                                                                                    │            [info] => Internal error, please try again later. If the problem persists, please contact our support.                                                                                                                                                                                                                                          │            [retry] => 1                                                                                                                                                                                                                                                                                                                                    │        )                                                                                                                                                                                                                                                                                                                                                   │                                                                                                                                                                                                                                                                                                                                                            │    [chargingSettings] => Array                                                                                                                                                                                                                                                                                                                             │        (                                                                                                                                                                                                                                                                                                                                                   │            [code] => 4105                                                                                                                                                                                                                                                                                                                                  │            [message] => The underlying system is not responding properly                                                                                                                                                                                                                                                                                   │            [group] => 2                                                                                                                                                                                                                                                                                                                                    │            [info] => Internal error, please try again later. If the problem persists, please contact our support.                                                                                                                                                                                                                                          │            [retry] => 1                                                                                                                                                                                                                                                                                                                                    │        )                                                                                                                                                                                                                                                                                                                                                   │                                                                                                                                                                                                                                                                                                                                                            │    [chargingStatus] => Array                                                                                                                                                                                                                                                                                                                               │        (                                                                                                                                                                                                                                                                                                                                                   │            [code] => 4105                                                                                                                                                                                                                                                                                                                                  │            [message] => The underlying system is not responding properly                                                                                                                                                                                                                                                                                   │            [group] => 2                                                                                                                                                                                                                                                                                                                                    │            [info] => Internal error, please try again later. If the problem persists, please contact our support.                                                                                                                                                                                                                                          │            [retry] => 1                                                                                                                                                                                                                                                                                                                                    │        )                                                                                                                                                                                                                                                                                                                                                   │                                                                                                                                                                                                                                                                                                                                                            │    [climatisationSettings] => Array                                                                                                                                                                                                                                                                                                                        │        (                                                                                                                                                                                                                                                                                                                                                   │            [code] => 4105                                                                                                                                                                                                                                                                                                                                  │            [message] => The underlying system is not responding properly                                                                                                                                                                                                                                                                                   │            [group] => 2                                                                                                                                                                                                                                                                                                                                    │            [info] => Internal error, please try again later. If the problem persists, please contact our support.                                                                                                                                                                                                                                          │            [retry] => 1                                                                                                                                                                                                                                                                                                                                    │        )                                                                                                                                                                                                                                                                                                                                                   │                                                                                                                                                                                                                                                                                                                                                            │    [climatisationStatus] => Array                                                                                                                                                                                                                                                                                                                          │        (                                                                                                                                                                                                                                                                                                                                                   │            [code] => 4105                                                                                                                                                                                                                                                                                                                                  │            [message] => The underlying system is not responding properly                                                                                                                                                                                                                                                                                   │            [group] => 2                                                                                                                                                                                                                                                                                                                                    │            [info] => Internal error, please try again later. If the problem persists, please contact our support.                                                                                                                                                                                                                                          │            [retry] => 1                                                                                                                                                                                                                                                                                                                                    │        )                                                                                                                                                                                                                                                                                                                                                   │                                                                                                                                                                                                                                                                                                                                                            │    [rangeStatus] => Array                                                                                                                                                                                                                                                                                                                                  │        (                                                                                                                                                                                                                                                                                                                                                   │            [code] => 4105                                                                                                                                                                                                                                                                                                                                  │            [message] => The underlying system is not responding properly                                                                                                                                                                                                                                                                                   │            [group] => 2                                                                                                                                                                                                                                                                                                                                    │            [info] => Internal error, please try again later. If the problem persists, please contact our support.                                                                                                                                                                                                                                          │            [retry] => 1                                                                                                                                                                                                                                                                                                                                    │        )                                                                                                                                                                                                                                                                                                                                                   │                                                                                                                                                                                                                                                                                                                                                            │)                                                                                                                                                                                                                                                                                                                                                           │                                                                                                                                                                                                                                                                                                                                                            │09:37:10.748587 [NOTICE] Ignoring these errors and continuing to attempt to decode data...                                                                                                                                                                                                                                                                  │array(2) {                                                                                                                                                                                                                                                                                                                                                  │  ["lightsStatus"]=>                                                                                                                                                                                                                                                                                                                                        │  array(2) {                                                                                                                                                                                                                                                                                                                                                │    ["carCapturedTimestamp"]=>                                                                                                                                                                                                                                                                                                                              │    string(20) "2021-04-22T06:14:43Z"                                                                                                                                                                                                                                                                                                                       │    ["lights"]=>                                                                                                                                                                                                                                                                                                                                            │    array(2) {                                                                                                                                                                                                                                                                                                                                              │      [0]=>                                                                                                                                                                                                                                                                                                                                                 │      array(2) {                                                                                                                                                                                                                                                                                                                                            │        ["name"]=>                                                                                                                                                                                                                                                                                                                                          │        string(5) "right"                                                                                                                                                                                                                                                                                                                                   │        ["status"]=>                                                                                                                                                                                                                                                                                                                                        │        string(3) "off"                                                                                                                                                                                                                                                                                                                                     │      }                                                                                                                                                                                                                                                                                                                                                     │      [1]=>                                                                                                                                                                                                                                                                                                                                                 │      array(2) {                                                                                                                                                                                                                                                                                                                                            │        ["name"]=>                                                                                                                                                                                                                                                                                                                                          │        string(4) "left"                                                                                                                                                                                                                                                                                                                                    │        ["status"]=>                                                                                                                                                                                                                                                                                                                                        │        string(3) "off"                                                                                                                                                                                                                                                                                                                                     │      }                                                                                                                                                                                                                                                                                                                                                     │    }                                                                                                                                                                                                                                                                                                                                                       │  }                                                                                                                                                                                                                                                                                                                                                         │  ["capabilityStatus"]=>                                                                                                                                                                                                                                                                                                                                    │  array(1) {                                                                                                                                                                                                                                                                                                                                                │    ["capabilities"]=>                                                             
```

**Comment by robske110** [comment]
Looks interesting, today I have also encountered a few error codes from the VW api. They seem to be doing more work on their systems at the moment.
As for the crashing part, IDDataLogger already tolerates a lot of errors and missing information, but a completely empty response is something that is, in my opinion, fine to cause a full crash. It should be behind restart scripts / a systemd service anyway. I am open to discussion on that topic though.

**Pull request merged**
