### PR TITLE
Adding Docker support

### PR DESCRIPTION
**Pull request by robske110**
This adds docker support using docker-compose.
There are three docker containers:
db - based on postgresql
web - based on php-apache
app - based on php

All configuration is done using environment variables.

Any testing and feedback is greatly appreciated!
To test follow the instructions found here: https://github.com/robske110/IDDataLogger/blob/docker/docs/docker.md
(Make sure to checkout the branch docker after cloning: `git checkout docker`)

TODO:
- [x] user & api key creation
- [x] documentation

### CODE REVIEW

**Comment by robske110** [comment]
Implementation and documenting done. Still needs more testing.

**Comment by GermanSheepDog** [comment]
Hello robske,

I tested the docker and every time I got issues with the parameters:
``` 
iddatalogger_app  | Stack trace:
iddatalogger_app  | #0 /usr/src/IDDataLogger/src/vwid/wizard/ConfigWizard.php(66): robske_110\vwid\wizard\ConfigWizard->writeJsonConfig(NULL, NULL, 'localhost', NULL, NULL, NULL, 'pgsql', 'config.json')
iddatalogger_app  | #1 /usr/src/IDDataLogger/src/vwid/wizard/ConfigWizard.php(19): robske_110\vwid\wizard\ConfigWizard->interactiveDBconfig()
iddatalogger_app  | #2 /usr/src/IDDataLogger/src/vwid/Server.php(49): robske_110\vwid\wizard\ConfigWizard->__construct()
iddatalogger_app  | #3 {main}
iddatalogger_app  |   thrown in /usr/src/IDDataLogger/src/vwid/wizard/ConfigWizard.php on line 122
iddatalogger_app  | Loading Logger...
iddatalogger_app  | 14:43:50.586593 [INFO] Starting ID DataLogger Version v0.0.4-InDev...
iddatalogger_app  | Loading Main...
iddatalogger_app  | 14:43:50.586936 [INFO] Reading config...
iddatalogger_app  | Loading ErrorUtils...
iddatalogger_app  | 14:43:50.587552 [CRITICAL] TypeError: "Cannot assign null to property robske_110\vwid\Main::$config of type array" (EXCEPTION) in "/usr/src/IDDataLogger/src/vwid/Main.php" at line 21
iddatalogger_app  | 14:43:50.587660 [DEBUG] #0 /usr/src/IDDataLogger/src/vwid/Server.php(104): robske_110\vwid\Main->__construct()
iddatalogger_app  | 14:43:50.587677 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
iddatalogger_app  | 14:43:50.587685 [INFO] Shutting down...
iddatalogger_app  | 14:43:50.587692 [CRITICAL] Forcibly shutting down while starting!
iddatalogger_app  | 14:43:50.587699 [DEBUG] >Closing Logger...
iddatalogger_app exited with code 0
``` 
My questions:
- Did the docker version use config/config.json?
- In which directory have I to store .env?
- It is enough, if I set only IDDATALOGGER_USERNAME, IDDATALOGGER_PASSWORD, IDDATALOGGER_IDVIEW_USERNAME and IDDATALOGGER_IDVIEW_PASSWORD in .env?

**Comment by GermanSheepDog** [comment]
Hello robske,

I found my first challenge: I forgot one comma in the first line of file config/config.json. Now this part worked.

My next problem is cd src/vwid/wizard/SetupWizard.php:
```
private function setupUser(){
	$username = $this->get("Enter the username for the new user");
	$password = $this->get("Now enter the password for the new user");
```
These values are empty and I got this error:
```
[Y]: > Enter the username for the new user: > Now enter the password for the new user: Loading ErrorUtils...
iddatalogger_app  | 15:52:27.894097 [CRITICAL] TypeError: "strlen(): Argument #1 ($string) must be of type string, null given" (EXCEPTION) in "/usr/src/IDDataLogger/src/vwid/wizard/SetupWizard.php" at line 46
iddatalogger_app  | 15:52:27.894150 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
iddatalogger_app  | 15:52:27.894159 [INFO] Shutting down...
iddatalogger_app  | 15:52:27.894164 [CRITICAL] Forcibly shutting down while starting!
iddatalogger_app exited with code 0
```
If a set the both values inline it worked. Which values are here used? From the file ".env"?

**Comment by robske110** [comment]
The docker versions uses the config.json, however you should not need to manually create it. In docker-start.sh it will be dynamically created from the environment variables.
Make sure to edit the file .env INSIDE the docker directory. Follow the instructions in https://github.com/robske110/IDDataLogger/blob/docker/docs/docker.md closely.
A correct command sequence would look like:
```bash
git clone https://github.com/robske110/IDDataLogger.git --recursive
cd IDDataLogger
checkout docker
cd docker
cp .env.example .env
nano .env # or with your alternative favourite editor
docker-compose up
```
If something still goes wrong, let me know. What system are you testing on? (linux / Mac / windows)

**Comment by GermanSheepDog** [comment]
Hello,
I have to do some changes. One point I didn't understand:
I have to copy .env.example to .env.
In the .env.example I found this:
```
DB_HOST=""
DB_NAME=""
DB_USER=""
DB_PASSWORD=null
DB_DRIVER="pgsql"
```
Farther I need the  environment variables IDDATALOGGER_USERNAME, IDDATALOGGER_PASSWORD, IDDATALOGGER_IDVIEW_USERNAME, IDDATALOGGER_IDVIEW_PASSWORD and IDDATALOGGER_WEB_PORT. Why are this variables not inside .env.example. Do I have to set these variables at the operating system level? Like this:
```
export IDDATALOGGER_USERNAME="My_VW_USERNAME" 
export IDDATALOGGER_PASSWORD="My_VW_PASSWORD" 
..
```
Currently I can login at VW with my workaround to set username and password inside ../src/vwid/wizard/SetupWizard.php::
```
private function setupUser(){
	$username = $this->get("Enter the username for the new user");
	$password = $this->get("Now enter the password for the new user");
```

**Comment by robske110** [comment]
You are still using the wrong .env.example. You need to use the .env.example inside the docker folder!
https://github.com/robske110/IDDataLogger/blob/docker/docker/.env.example

**Comment by GermanSheepDog** [comment]
Yes, I copied the wrong .env.example to this request.

But I used a script to generate the input of the .env:
```
git clone https://github.com/robske110/IDDataLogger.git
cd IDDataLogger
mkdir docker
echo "IDDATALOGGER_USERNAME=\"***xxx@xxx.de***\"" > example.env
echo "IDDATALOGGER_PASSWORD=\"***secret***\"" >> example.env
echo "IDDATALOGGER_IDVIEW_USERNAME=\"admin\"" >> example.env
echo "IDDATALOGGER_IDVIEW_PASSWORD=\"***secret***\"" >> example.env
echo "IDDATALOGGER_WEB_PORT=8888" >> example.env
mv example.env ".env"
```
I think this is correct.

It worked if I use the workaround to set username and password inside ../src/vwid/wizard/SetupWizard.php.

**Comment by robske110** [comment]
What happens without your workaround?
The IDVIEW_PASS and USER env variables should prevent the setupUser function to be called.
https://github.com/robske110/IDDataLogger/blob/7f282c5e362eb633e5d8f2c30cd317b3cdc32d9d/docker/docker-start.sh#L4

**Comment by GermanSheepDog** [comment]
I am missing the values of IDDATALOGGER_USERNAME and the IDDATALOGGER_PASSWORD in SetupWizard.php. These values are null!

I used a Mac with Big Sur (11.2.3). At the next weekend I will analyse the issue.

**Comment by robske110** [comment]
I will now be merging this PR. @GermanSheepDog If you find some time to test again (from master) and manage to reproduce the issue, feel free to open an issue.

**Pull request merged**
